### ISSUE TITLE
footer: fix alignment issues on screens of varying sizes

### ISSUE THREAD

**Issue by lness02** [uclaacm/cyber.uclaacm.com#20]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/93940826/229653659-41e9afb5-4fdb-4be1-8ca5-c8a526bcd405.png">
See above for an example. Try resizing your screen to see it for yourself.

**Comment by bliutech** [comment]
I think this is something that can be resolved by **media queries**. Some introductory documentation below and then some specific documentation for SCSS syntax.

**Media Queries:** https://www.w3schools.com/css/css3_mediaqueries.asp
**SCSS Documentation - CSS At-Rules**: https://sass-lang.com/documentation/at-rules/css

**Comment by bliutech** [comment]
This may also require a redesign to note what a footer may look like for this. Potential behavior may be to think about what a squeezed footer looks like. Additionally, another idea would be to simply hide the footer.

**Comment by bliutech** [comment]
Simplified footer. Closing this issue.
