### ISSUE TITLE
front page: image carousel

### ISSUE THREAD

**Issue by lness02** [uclaacm/cyber.uclaacm.com#30]

**Comment by r2dev2** [comment]
imma put this in `/about` for now in a component `<Carousel />` so we can move it around later

**Comment by r2dev2** [comment]
@bliutech btw gary still working on it

**Comment by r2dev2** [comment]
Current progress

https://github.com/uclaacm/cyber.uclaacm.com/assets/50760816/d814b742-8c01-4754-bf6f-92843d14ebad
