### ISSUE TITLE
Blog: Have buttons for articles (drawing from backend) that redirect you to the article page

### ISSUE THREAD

**Issue by lness02** [uclaacm/cyber.uclaacm.com#41]

**Comment by bliutech** [comment]
Backend is not necessary. We can just draw from `data/`

**Comment by bliutech** [comment]
Updating specifications for @danieltherealyang. Buttons are not necessary for this implementation. On the `/blog` page, include a component that lists all of the blog posts in the `/data/blog` directory. Include details about each blog such as the title, date, author, etc to help provide some cards representing each blog post. This will allow users to navigate to all of our blog posts so be sure to take a look at the Figma for reference and get a sense of the what it should look and behave like.
